### ISSUE TITLE
Convert code to Kotlin and possible Architecture change

### ISSUE THREAD

**Issue by Lekky71** [Lekky71/IAddContacts#1]
Currently, the code is in Java, for future maintenance, I'm thinking of:

- [x]  Converting to Kotlin

- [x] Migrating to AndroidX

- [x] Changing architecture to MVVM if needed

**Comment by aravp-mobile** [comment]
I will work on this issue.

**Comment by Lekky71** [comment]
Awesome! Looking forward to your PR.

**Comment by aravp-mobile** [comment]
Yeah Sure.

**Comment by Khalidtoak** [comment]
created a PR for this sir, please check😊

**Comment by Lekky71** [comment]
Great job @Khalidtoak
